# start with: docker-compose up -d
# mongodb://olle:9dksert9we9@localhost:27017/keystonejs
# mongodb://root:kldfg789@localhost:27017/admin

version: '3.1'

services:

  mongo:
    image: mongo:4.2.2-bionic
    # restart: always
    container_name: keystone-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: kldfg789
      # Used by docker-entrypoint-initdb.d
      MONGO_INITDB_DATABASE: keystonejs
      MONGO_INITDB_ADMIN_USERNAME: olle
      MONGO_INITDB_ADMIN_PASSWORD: 9dksert9we9
    volumes:
      - "./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/"  
      # Cannot save db on Windows, write access errors  
      # - ./mongodbdata:/data/db
    ports: 
      - 27017:27017

  mongo-express:
    image: mongo-express
    # restart: always
    container_name: keystone-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: kldfg789

  node:
    image: my-registry.example.com/my-cool-keystone-app:v1.0
    # restart: always
    container_name: keystone-node
    ports:
      - "3000:3000"
    environment: 
      MONGO_URI: mongodb://olle:9dksert9we9@keystone-mongo:27017/keystonejs  
      NODE_ENV: production keystone start
    
                